import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import DataProvider from "@/context/DataProvider";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`h-full`}
    >
      <body className={`${geistSans.className} min-h-full flex flex-col bg-[#F8FAFC]`}>
        <Navbar />
        <DataProvider>
          <ToastContainer />
          {children}
        </DataProvider>
        <Footer />
      </body>
    </html>
  );
}
